spring.application.name=faturamento-api
# H2 Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:tcp://localhost:9093/financeiro}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pirogue

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true